version: "3.8"

services:
  ase-to-http-api:
    build: ./src/.
    ports:
      - "${PORT}:80" # you can set this from .env
    environment:
      - GIN_MODE=release
      - TOKEN=${TOKEN}
    restart: unless-stopped
